# put your configuration values here

[runtime]
log_level="INFO"  # WARNING = quiet; INFO = see extract/load activity; DEBUG = verbose
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true
